react-recap-issue3
SylvieDoumet/React-Recap-Project pull request #10
Opened 2024-06-12 10:51 UTC by SylvieDoumet

Issue 3 - please review and confirm merging option

2024-06-12 13:51 UTC, JessicaLoers requested changes
**Hi @SylvieDoumet** 

⚠️ The feature to delete a color isn't working. Therefore, this issue is not yet resolved. 
Please thoroughly test your application before submitting your code for review. Ensure that all acceptance criteria are met.

When programming, it isn't only advisable but also very sensible to use the Dev Tools. This would have helped you catch the reference error. 😉

**Questions:**
- Why did you choose to use arrow functions for the handlers?
- Why are the component imports incorrect? Did you check this? Is the ColorInput folder in the correct location? 

**Additional Notes:**
Please work with the project board and adhere to the workflow:
- Move any issue you are currently working on to the "In Progress" column.
- Close issues that you have already completed.
- Please deploy to Vercel.

2024-06-12 13:51 UTC, JessicaLoers commented on src/Components/Color/Color.jsx
> +      <button onClick={onDelete}>Delete</button>
Please take a look into the dev tools.  You will see the following error message.
```
ReferenceError: onDelete is not defined
```

**What could be the reason for this?**

2024-06-12 13:51 UTC, JessicaLoers commented on src/App.jsx
> +};
Why did you choose to use arrow functions for the handlers? 

You update the state `confirmDeleteId ` from `null` to `null`? Think about what exactly the goal is.
 Have you checked the functionality of your app?

2024-06-12 13:51 UTC, JessicaLoers commented on src/App.jsx
> +        onDelete={() => handleConfirmDelete(color.id)}
Shouldn't this function delete the colour? Why are using the `handleConfirmDelete` ?
Have you checked the functionality in your app?

2024-06-12 13:51 UTC, JessicaLoers commented on src/App.jsx
> +  setConfirmDeleteId(null);
Why did you choose to use arrow functions for the handlers? 

Is the function parameter necessary?

You update the state `confirmDeleteId ` from `null` to `null`? Think about what exactly the goal is.
 Have you checked the functionality of your app?

2024-06-12 13:51 UTC, JessicaLoers commented on src/App.jsx
> +};
Why did you choose to use arrow functions for the handlers?

Is the function parameter necessary?

You update the state confirmDeleteId  from `null` to `null`? Think about what exactly the goal is.
Have you checked the functionality of your app?

2024-06-12 13:51 UTC, JessicaLoers commented on src/App.jsx
> +)}
If you want to work with the `setConfirmDeleteId` state, it's important that you specify the corresponding ID.

Here you call the `handleDeleteColor` function and pass it a state setter function. However, your delete function expects an ID - that's wild. 🎢

2024-06-13 14:29 UTC, SylvieDoumet commented
Ich habe jetzt alle Anmerkungen bearbeitet - habe allerdings in der ColorForm.jsx immer noch Importprobleme und sehe nicht wo der Fehler liegt

2024-06-14 08:11 UTC, merged